config/routes.rb
Rails.application.routes.draw do
  resources :book_reviews
  get 'users/show'
  get 'static_pages/home'
  devise_for :users
  resources :books
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "static_pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
end

app/models/book_review.rb
class BookReview < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name, :age, :avatar, :password, :password_confirmation])

    devise_parameter_sanitizer.permit(:sign_in, keys: [:login, :email, :password, :remember_me])

    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :age, :avatar, :email, :password, :password_confirmation, :current_password])
  end

end

app/controllers/book_reviews_controller.rb
class BookReviewsController < ApplicationController
  before_action :set_book_review, only: %i[ show edit update destroy ]

  # GET /book_reviews or /book_reviews.json
  def index
    @book_reviews = BookReview.all
  end

  # GET /book_reviews/1 or /book_reviews/1.json
  def show
  end

  # GET /book_reviews/new
  def new
    @book_review = BookReview.new
  end

  # GET /book_reviews/1/edit
  def edit
  end

  # POST /book_reviews or /book_reviews.json
  def create
    @book_review = BookReview.new(book_review_params)

    respond_to do |format|
      if @book_review.save
        format.html { redirect_to book_review_url(@book_review), notice: "Book review was successfully created." }
        format.json { render :show, status: :created, location: @book_review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_reviews/1 or /book_reviews/1.json
  def update
    respond_to do |format|
      if @book_review.update(book_review_params)
        format.html { redirect_to book_review_url(@book_review), notice: "Book review was successfully updated." }
        format.json { render :show, status: :ok, location: @book_review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_reviews/1 or /book_reviews/1.json
  def destroy
    @book_review.destroy

    respond_to do |format|
      format.html { redirect_to book_reviews_url, notice: "Book review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book_review
    @book_review = BookReview.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def book_review_params
    params.require(:book_review).permit(:user_id, :book_id, :review)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
    @reviews = BookReview.where(book_id: params[:id])
  end

  # GET /books/1 or /books/1.json
  def show()
    @reviews = BookReview.where(book_id: params[:id])
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:title, :number_of_pages, :image, :detail)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_reviews_helper.rb
module BookReviewsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/book_reviews/_book_review.html.erb
<div id="<%= dom_id book_review %>">
  <p>
    <strong>User:</strong>
    <%= book_review.user_id %>
  </p>

  <p>
    <strong>Book:</strong>
    <%= book_review.book_id %>
  </p>

  <p>
    <strong>Review:</strong>
    <%= book_review.review %>
  </p>

</div>

app/views/book_reviews/_form.html.erb
<%= form_with(model: book_review) do |form| %>
  <% if book_review.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book_review.errors.count, "error") %> prohibited this book_review from being saved:</h2>

      <ul>
        <% book_review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :book_id, style: "display: block" %>
    <%= form.number_field :book_id %>
  </div>

  <div>
    <%= form.label :review, style: "display: block" %>
    <%= form.text_area :review %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/book_reviews/edit.html.erb
<h1>Editing book review</h1>

<%= render "form", book_review: @book_review %>

<br>

<div>
  <%= link_to "Show this book review", @book_review %> |
  <%= link_to "Back to book reviews", book_reviews_path %>
</div>

app/views/book_reviews/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Book reviews</h1>

<div id="book_reviews">
  <% @book_reviews.each do |book_review| %>
    <%= render book_review %>
    <p>
      <%= link_to "Show this book review", book_review %>
    </p>
  <% end %>
</div>

<%= link_to "New book review", new_book_review_path %>

app/views/book_reviews/new.html.erb
<h1>New book review</h1>

<%= render "form", book_review: @book_review %>

<br>

<div>
  <%= link_to "Back to book reviews", book_reviews_path %>
</div>

app/views/book_reviews/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book_review %>

<div>
  <%= link_to "Edit this book review", edit_book_review_path(@book_review) %> |
  <%= link_to "Back to book reviews", book_reviews_path %>

  <%= button_to "Destroy this book review", @book_review, method: :delete %>
</div>

app/views/books/_book.html.erb
<% book_review = BookReview.new %>
<div id="<%= dom_id book %>">
  <p>
    <strong>Title:</strong>
    <%= book.title %>
  </p>

  <p>
    <strong>Number of pages:</strong>
    <%= book.number_of_pages %>
  </p>

  <p>
    <strong>Detail:</strong>
    <%= book.detail %>
  </p>

  <!--  <p>-->
  <!--    <strong>Image:</strong>-->
  <%#= image_tag(book.image, style: 'width:200px;height:150px') %>
  <!--  </p>-->

  <%= form_with model: book_review, url: "/book_reviews", method: :post do |form| %>
    <div>
      <%= form.hidden_field :user_id, value: current_user.id %>
    </div>

    <div>
      <%= form.hidden_field :book_id, value: book.id %>
    </div>

    <div>
      <%= form.label :review, style: "display: block" %>
      <%= form.text_area :review %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
  <p>Review list</p>
  <% if @reviews != nil %>
    <ul style="list-style-type:circle">
      <% @reviews.each do |review| %>
        <li style="margin-left: 8px">
          ・ <%= review.review %> (<i><%= review.user.name %></i>)
        </li>
      <% end %>
    </ul>
  <% end %>

</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :number_of_pages, style: "display: block" %>
    <%= form.number_field :number_of_pages %>
  </div>

  <div>
    <%= form.label :detail, style: "display: block" %>
    <%= form.text_area :detail %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Books</h1>

<div id="books">
  <% @books.each do |book| %>
    <% @reviews = BookReview.where(book_id: book[:id]) %>
    <% book_review = BookReview.new %>
    <div id="<%= dom_id book %>">
      <p>
        <strong>Title:</strong>
        <%= book.title %>
      </p>

      <p>
        <strong>Number of pages:</strong>
        <%= book.number_of_pages %>
      </p>

      <p>
        <strong>Detail:</strong>
        <%= book.detail %>
      </p>

      <!--  <p>-->
      <!--    <strong>Image:</strong>-->
      <%#= image_tag(book.image, style: 'width:200px;height:150px') %>
      <!--  </p>-->

      <%= form_with model: book_review, url: "/book_reviews", method: :post do |form| %>
        <div>
          <%= form.hidden_field :user_id, value: current_user.id %>
        </div>

        <div>
          <%= form.hidden_field :book_id, value: book.id %>
        </div>

        <div>
          <%= form.label :review, style: "display: block" %>
          <%= form.text_area :review %>
        </div>

        <div>
          <%= form.submit %>
        </div>
      <% end %>
      <p>Review list</p>
      <% if @reviews != nil %>
        <ul style="list-style-type:circle">
          <% @reviews.each do |review| %>
            <li style="margin-left: 8px">
              ・ <%= review.review %> (<i><%= review.user.name %></i>)
            </li>
          <% end %>
        </ul>
      <% end %>

    </div>

    <p>
      <%= link_to "Show this book", book %>
    </p>
  <% end %>
</div>

<%= link_to "New book", new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
  <%= link_to "Edit this book", edit_book_path(@book) %> |
  <%= link_to "Back to books", books_path %>

  <%= button_to "Destroy this book", @book, method: :delete %>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <title>Ruby</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
</head>

<body style="display: flex;flex-direction: column;min-height: 100vh">
<header style="display:flex;flex-direction: row;align-items: center;background-color: #2E2F30;padding-inline: 40px;padding-block: 12px;color: white">
  <a href="/" style="padding-inline: 16px;padding-block: 12px;">ホーム</a>
  <span style="flex: 1"></span>
  <% if user_signed_in? %>
    <a href="/users/show">
      <%= current_user.name||current_user.email %>
    </a>
    <%= button_to "サインアウト", destroy_user_session_path, method: :delete, :style => 'margin-left: 16px;padding-inline: 16px;padding-block: 12px;background-color: #FF6347;border-radius: 12px;cursor: pointer' %>
  <% else %>
    <a href="/users/sign_in">サインイン</a>
    <a href="/users/sign_up" style="margin-left: 16px;padding-inline: 16px;padding-block: 12px;background-color: #1E90FF;border-radius: 12px;">ユーザ登録</a>
  <% end %>
</header>
<div style="flex: 1">
  <%= yield %>
</div>
</body>
</html>

app/views/static_pages/home.html.erb
<div style="padding: 12px">
  <h1>ホームページ</h1>
  <% if user_signed_in? %>
    <a href="/books">本一覧を見る</a>
  <% end %>
</div>

app/views/users/show.html.erb
<div style="padding: 12px">
  <h1>プロフィール</h1>
  <h3>メールアドレス</h3>
  <p>Name: <%= current_user.name %></p>
  <p>Age: <%= current_user.age %></p>
  <p>Email: <%= current_user.email %></p>
  <p>Avatar: <%= image_tag(current_user.avatar, style: 'width:200px;height:200px') %> </p>
</div>